<a href="https://colab.research.google.com/github/chetools/STEMUnleashed2025/blob/main/AutomaticDerivatives.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Optimization is central to just about everything we want to do
#We develop models to simulate processes on a computer
#Models will have adjutable parameters that mirror real life parameters that we wish to adjust to optimize the process
# Silence is a wORD, phrase, and even a sentence

In [1]:
import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", True)
import numpy as np
from scipy.optimize import minimize

In [7]:
def caroline(x):
    return jnp.sin(2*x[0])*jnp.exp(x[1]*jnp.cos(x[2]+x[0]))

def will(z):
    return z[0]*jnp.exp(z[1])*caroline(z[2:])

In [8]:
z=jnp.array([0.1,0.2,-0.3,1.,2])

In [9]:
will(z)

Array(-0.06062838, dtype=float32)

In [10]:
will_grad = jax.grad(will)

In [11]:
will_grad(z)

Array([-0.60628384, -0.06062838,  0.23736356,  0.00781164,  0.06012304],      dtype=float32)

In [12]:
(will(z+jnp.array([1e-4, 0.,0.,0, 0])) - will(z))/1e-4

Array(-0.606291, dtype=float32)

In [ ]:
x=jnp.array([0.1001,0.3,-0.2])

In [ ]:
caroline(x)

Array(0.26803893, dtype=float32)

In [2]:
def f(t):
    return 2*(t**3)

In [3]:
def finite_difference(g, x, h):
    return (g(x+h) - g(x))/h

In [5]:
def v(t, h):
    return finite_difference(f, t, h)

In [4]:
for i in range(0,-17,-1):
    h=10**i
    fd = finite_difference(f, 0.5, h)
    exact = 6*(0.5)**2
    error = abs(fd - exact)
    print(f'{i} {fd} {error}')

0 6.5 5.0
-1 1.8199999999999994 0.3199999999999994
-2 1.5302000000000038 0.03020000000000378
-3 1.5030019999999755 0.0030019999999755242
-4 1.5003000199997896 0.00030001999978956917
-5 1.5000300001954956 3.0000195495594184e-05
-6 1.5000030000322795 3.000032279487641e-06
-7 1.5000002989706829 2.989706828770977e-07
-8 1.5000000352927145 3.529271452862304e-08
-9 1.4999999575771028 4.242289719513792e-08
-10 1.5000001241105565 1.2411055649863556e-07
-11 1.5000001241105565 1.2411055649863556e-07
-12 1.4999668174198177 3.318258018225606e-05
-13 1.500466417780899 0.0004664177808990644
-14 1.4988010832439613 0.0011989167560386704
-15 1.498801083243961 0.0011989167560388925
-16 1.6653345369377348 0.1653345369377348


In [6]:
for i in range(0,-17,-1):
    h=10**i
    fd = finite_difference(lambda t: v(t, h), 0.5, h)
    exact = 12*0.5
    error = abs(fd - exact)
    print(f'{i} {fd} {error}')

0 18.0 12.0
-1 7.199999999999993 1.199999999999993
-2 6.119999999999459 0.1199999999994592
-3 6.012000000055195 0.012000000055195414
-4 6.0012000036024915 0.0012000036024915062
-5 6.00011929030586 0.00011929030585999811
-6 6.000033803132965 3.380313296474924e-05
-7 6.006306563222097 0.006306563222096884
-8 6.661338147750939 0.6613381477509392
-9 0.0 6.0
-10 0.0 6.0
-11 0.0 6.0
-12 0.0 6.0
-13 0.0 6.0
-14 0.0 6.0
-15 0.0 6.0
-16 0.0 6.0


In [ ]:
# prompt: using plotly create a plot of the rosenbrock function

import plotly.graph_objects as go
import numpy as np

def rosenbrock(x, y, a=1, b=100):
    return (a - x)**2 + b * (y - x**2)**2

x = np.linspace(-2, 2, 100)
y = np.linspace(-1, 3, 100)
X, Y = np.meshgrid(x, y)
Z = rosenbrock(X, Y)

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(
    title='Rosenbrock function',
    scene = dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='f(X,Y)'),
    autosize=False,
    width=500,
    height=500,
    margin=dict(l=65, r=50, b=65, t=90)
)

fig.show()


In [16]:
def rosenbrock(v):
    x,y = v
    a=1
    b=100
    return (a - x)**2 + b * (y - x**2)**2

In [17]:
minimize(rosenbrock, [2,2.])

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.8932783589357527e-11
        x: [ 1.000e+00  1.000e+00]
      nit: 30
      jac: [ 5.274e-06 -2.506e-06]
 hess_inv: [[ 5.168e-01  1.032e+00]
            [ 1.032e+00  2.066e+00]]
     nfev: 105
     njev: 35

In [2]:
@jax.jit
def rosenbrockNd(x):
    return jnp.sum(10000*(x[:-1:2]**2 - x[1::2])**2 + (1 - x[:-1:2])**2)

In [3]:
rosen_grad = jax.jit(jax.grad(rosenbrockNd))

In [8]:
rnd=np.random.RandomState(123)
x0=rnd.uniform(-2,2, size=300)

In [9]:
sol=minimize(rosenbrockNd, x0, jac=rosen_grad)
sol

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.0093221328732512e-10
        x: [ 1.000e+00  1.000e+00 ...  1.000e+00  1.000e+00]
      nit: 3912
      jac: [-1.140e-06  3.175e-07 ... -3.777e-07 -3.747e-07]
 hess_inv: [[ 3.781e-01  7.564e-01 ...  2.249e-03  4.492e-03]
            [ 7.564e-01  1.513e+00 ...  4.502e-03  8.993e-03]
            ...
            [ 2.249e-03  4.502e-03 ...  2.394e-02  4.786e-02]
            [ 4.492e-03  8.993e-03 ...  4.786e-02  9.574e-02]]
     nfev: 4270
     njev: 4270

In [46]:
sol.x

array([1.00000186, 1.00000375, 0.99999706, 0.99999415, 0.9999973 ,
       0.99999462])