<a href="https://colab.research.google.com/github/chetools/STEMUnleashed2025/blob/main/NewtonMethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import jax
import jax.numpy as jnp
jax.config.update('jax_enable_x64',True)
from plotly.subplots import make_subplots

In [29]:
def f(x):
    return (x)*(x-3)*(x+2)*(x-5)
fprime = jax.grad(f)

In [24]:
xplot = np.linspace(-3,6,100)
fig = make_subplots()
fig.add_scatter(x=xplot, y=f(xplot), mode='lines')
fig.update_layout(width=600, height=400, template='plotly_dark')

In [25]:
def newton(g, gprime, x0, niter=20, tol=1e-12):
    g_vals = [g(x0)]
    x_vals = [x0]

    xk=x0
    for i in range(niter):
        xk1 = xk - g(xk)/gprime(xk)
        gxk1 = g(xk1)
        g_vals.append(gxk1)
        x_vals.append(xk1)
        if np.abs(gxk1)<tol:
            break
        xk = xk1
    return x_vals, g_vals,

In [26]:
x_newton, y_newton = newton(f, fprime, 2.)

In [27]:
fig = make_subplots()
fig.add_scatter(x=xplot, y=f(xplot), mode='lines')
fig.add_scatter(x=x_newton, y=y_newton, mode='markers')
fig.update_layout(width=600, height=400, template='plotly_dark')

In [30]:
fig = make_subplots()
fig.add_scatter(x=xplot, y=f(xplot), mode='lines', name='f')
fprime_vals = [fprime(x) for x in xplot]

fig.add_scatter(x=xplot, y=fprime_vals, mode='lines', name='fprime')
fig.update_layout(width=600, height=400, template='plotly_dark')

In [31]:
def rosenbrock(v):
    x,y = v
    return (1 - x)**2 + 100 * (y - x**2)**2

In [33]:
rosen_grad= jax.grad(rosenbrock)

In [34]:
rosen_grad(np.array([1.5,1.5]))

Array([ 451., -150.], dtype=float64)

In [35]:
rosen_jac_grad = jax.jacobian(rosen_grad)

In [36]:
rosen_jac_grad(np.array([1.5,1.5]))

Array([[2102., -600.],
       [-600.,  200.]], dtype=float64)

In [43]:
def newton_minimization(f, v0, max_iter=10):
    f_grad = jax.grad(f)
    f_jac_grad = jax.jacobian(f_grad)

    v_list=[v0]
    vold = v0
    for i in range(max_iter):
       h = np.linalg.solve(f_jac_grad(vold)  , -f_grad(vold))
       vnew = vold + h
       v_list.append(vnew)
       vold= vnew

    return v_list

In [44]:
newton_minimization(rosenbrock, np.array([1.5,1.5]))

[array([1.5, 1.5]),
 array([1.49668874, 2.24006623]),
 array([1.0010868 , 0.75655349]),
 array([1.00106512, 1.00213137]),
 array([1.        , 0.99999887]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.])]

In [45]:
minimize?

Object `minimize` not found.


In [ ]:
x = np.linspace(-2, 2, 100)
y = np.linspace(-1, 3, 100)
X, Y = np.meshgrid(x, y)
Z = rosenbrock(X, Y)

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(
    title='Rosenbrock function',
    scene = dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='f(X,Y)'),
    autosize=False,
    width=500,
    height=500,
    margin=dict(l=65, r=50, b=65, t=90)
)

fig.show()